version: '2.1'
services:
  app:
    build: .
    image: zenodo:latest
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672//"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SESSION_COOKIE_SECURE=True"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql://zenodo:zenodo@db/zenodo"
      - "INVENIO_WSGI_PROXIES=2"
      - "FLASK_DEBUG=${FLASK_DEBUG:-on}"
  lb:
    build: ./docker/haproxy/
    image: zenodo-lb:latest
    restart: "always"
    #ports:
    #  - "129.232.230.132:80:80"
    #  - "129.232.230.132:443:443"
    #  - "129.232.230.132:8080:8080"
  frontend:
    build: ./docker/nginx/
    image: zenodo-frontend:latest
    restart: "always"
    #ports:
    #  - "129.232.230.132:81:80"
    #  - "129.232.230.132:444:443"
  cache:
    image: redis
    restart: "always"
    read_only: true
    expose:
      - 6379
    #ports:
    #  - "129.232.230.132:6379:6379"
  db:
    build: ./docker/postgres/
    image: zenodo-postgres
    command: postgres
    restart: "always"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=admin"
    expose:
      - 5432
    #ports:
    #  - "129.232.230.132:5432:5432"
  mq:
    image: rabbitmq:3-management
    restart: "always"
    expose:
      - 15672
      - 5672
    #ports:
    #  - "129.232.230.132:15672:15672"
    #  - "5672:5672"
  es:
    build: ./docker/es/
    image: zenodo-es:2.3
    restart: "always"
    expose:
      - 9200
      - 9300
    #ports:
    #  - "129.232.230.132:9200:9200"
    #  - "129.232.230.132:9300:9300"
  kibana:
    build: ./docker/kibana/
    image: zenodo-kibana:4.3
    restart: "always"
    command: kibana
    expose:
      - 5601
    #ports:
    #  - "129.232.230.132:5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://es:9200"
  flower:
    image: mher/flower
    command: --broker=amqp://guest:guest@mq:5672// --broker_api=http://guest:guest@mq:15672/api/
    expose:
      - 5555
    #ports:
    #  - "129.232.230.132:5555:5555"
